accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout, name="logout"),
    path('login/', views.login, name="login"),
    path('delete/', views.delete, name="delete"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
    path('change_profile/', views.change_profile, name="change_profile"),
    path('<int:user_id>/vuefollow/', views.vue_follow),
    path('<int:user_id>/checkfollow/', views.check_follow),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.profile, name="profile"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views
app_name = "posts"

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.list, name="list"),
    path('<int:post_id>/delete/', views.delete, name="delete"),
    path('<int:post_id>/update/', views.update, name="update"),
    path('<int:post_id>/comments/create', views.create_comments, name="create_comments"),
    path('<int:post_id>/like/', views.like, name="like"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")
    
class Profile(models.Model):
    description = models.TextField(blank=True)
    nickname = models.CharField(max_length=40, blank=True)
    image = models.ImageField(blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"<{self.user.username}>, nickname: {self.nickname}, description: {self.description}"

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=140)
    image = models.ImageField(blank=True)
    # User와의 YGGR 1 (1:N)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # User와의 YGGR 2 (M:N) Like
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'description', 'image']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from .forms import ProfileForm
from django.http import JsonResponse

# Create your views here.
def signup(request):
    # 회원가입
    if request.method == "POST":
        print(request.POST)
        form = CustomUserCreationForm(request.POST)
        print(form)
        if form.is_valid():
            user = form.save()
            # 가입된 유저의 Profile 레코드도 함께 생성
            Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect('posts:list')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})
    

def login(request):
    if request.method == "POST":
        # 실제 로그인(세션의 유저 정보를 넣는다.)
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
        return redirect('posts:list')
    else:
        # 유저로부터 username과 비밀번호를 받는다.
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form':form})

def logout(request):
    auth_logout(request)
    return redirect('posts:list')
    
def profile(request, username):
    # username을 가진 유저의 상세 정보를 보여주는 페이지
    profile = get_object_or_404(get_user_model(), username=username) 
    # User.objects.get(username=username) 이거랑 같다.
    return render(request, 'accounts/profile.html', {'profile': profile})
    
def delete(request):
    # POST 계정을 삭제한다 == DB에서 user를 삭제한다.
    if request.method == "POST":
        request.user.delete()
        return redirect('accounts:signup')
    # GET -> 진짜 삭제 하시겠습니까?
    return render(request, 'accounts/delete.html')
    
@login_required
def follow(request, user_id):
    person = get_object_or_404(get_user_model(), pk=user_id)
    # 만약 이미 팔로우한 사람이라면
    if request.user in person.followers.all():
        person.followers.remove(request.user) # user=request.user
    #  -> 언팔
    # 아니면,
    else:
        person.followers.add(request.user)
    #  -> 팔로우
    return redirect('profile', person.username)
    
@login_required
def change_profile(request):
    # 프로필 정보 수정
    if request.method == "POST":
        print(request.POST)
        profile_form = ProfileForm(data=request.POST,instance=request.user.profile, files=request.FILES) # 
        print(profile_form)
        if profile_form.is_valid():
            profile_form.save()
        return redirect('profile', request.user.username)
    else:
        profile_form = ProfileForm(instance=request.user.profile)
        return render(request, 'accounts/change_profile.html', {'profile_form':profile_form})
        
@login_required
def vue_follow(request, user_id):
    # follow를 시키거나, unfollow를 시키거나 둘 중에 하나를 한다. 
    # => JSON으로 받아서 => Vue를 통해 render
    person = get_object_or_404(get_user_model(), pk=user_id)
    # 만약 이미 팔로우한 사람이라면
    if request.user in person.followers.all():
        person.followers.remove(request.user) # user=request.user
        followed = False
    #  -> 언팔
    # 아니면,
    else:
        person.followers.add(request.user)
        followed = True
    #  -> 팔로우
    return JsonResponse({'followed': followed})
    
@login_required
def check_follow(request, user_id):
    person = get_object_or_404(get_user_model(), pk=user_id)
    if request.user in person.followers.all():
        followed = True
    else:
        followed = False
    return JsonResponse({'followed': followed})

accounts/templates/accounts/change_profile.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1>프로필수정</h1>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form profile_form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">프로필 변경</button>
  {% endbuttons %}
</form>

{% endblock%}

accounts/templates/accounts/delete.html
{% extends 'base.html' %}
{% block body %}
  <h1>정말로 탈퇴하실 건가요 ㅠㅠ</h1>
  <form action="{% url 'accounts:delete' %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-dark" type="submit">가지마세요</button>
  </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1>로그인</h1>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">로그인</button>
  {% endbuttons %}
</form>

{% endblock%}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
<div class="row">
  <div class="col-3">
    {% if profile.profile.image %}
    <img class="rounded-circle img-fluid" src="{{ profile.profile.image.url }}">
    {% else %}
    <img class="rounded-circle img-fluid" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png">
    {% endif %}
    <h1>{{ profile.username }} 
    {% if user != profile %}
      {% if user in profile.followers.all %}
        <a class="btn btn-primary" href="{% url 'accounts:follow' profile.id %}">언팔로우</a>
      {% else %}
        <a class="btn btn-info" href="{% url 'accounts:follow' profile.id %}">팔로우</a>
      {% endif %}
      
    {% endif %}
    </h1>
    
    <div id="app">
      <!--버튼을 클릭하면, 팔로우할 수 있는 버튼-->
      <button v-show="loading" @click="follow({{ profile.id }})" :class="{'btn': true, 'btn-info': !followed, 'btn-dark': followed}">팔로우</button>
      [[ text ]]
    </div>
  
  </div>
  <div class="col-9">
      <div>
    <strong>{{ profile.profile.nickname }}</strong>
    {{ profile.profile.description }}
    </div>
  </div>
</div>

  {% if user == profile %}
  <a class="btn btn-danger" href="{% url 'accounts:delete' %}">회원탈퇴</a>
  <a class="btn btn-danger" href="{% url 'accounts:change_profile' %}">프로필변경</a>
  {% endif %}
  
  <div class="row">
    <!-- 해당 유저가 작성한 모든 post를 보여줌 -->
    {% for post in profile.post_set.all %}
    <div class="col-4">
      <img src="{{ post.image.url }}" class="img-fluid">      
    </div>
    {% endfor %}
  </div>
  <script>
    const app = new Vue({
      delimiters: ['[[', ']]'],
      el: '#app',
      data: {
        'text':'뷰 작동 한다리',
        followed: '', //false
        loading: false,
      },
      methods: {
        follow: function(profile_id) {
          axios.get(`/accounts/${profile_id}/vuefollow/`)
          .then((response)=>{return response.data})
          .then((data)=>{this.followed = data.followed})
        },
        checkFollow: function(profile_id){
          axios.get(`/accounts/${profile_id}/checkfollow/`)
          .then((response)=>{return response.data})
          .then((data)=>{
            this.followed = data.followed
            this.loading = true
          })
        }
      },
      beforeMount: function(){
        // 뭘 해야하나? django에게 물어봐 follow 여부를 확인하고, 해당하는 값을 보여준다.
        this.checkFollow({{ profile.id }})
      }
    })
  </script>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1>회원가입</h1>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">회원가입</button>
  {% endbuttons %}
</form>

{% endblock%}