instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.profile, name="profile"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views
app_name = "posts"

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.list, name="list"),
    path('<int:post_id>/delete/', views.delete, name="delete"),
    path('<int:post_id>/update/', views.update, name="update"),
    path('<int:post_id>/comments/create', views.create_comments, name="create_comments"),
    path('<int:post_id>/like/', views.like, name="like"),
]

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=140)
    image = models.ImageField(blank=True)
    # User와의 YGGR 1 (1:N)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # User와의 YGGR 2 (M:N) Like
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
    content = forms.CharField(
        label="content", 
        widget=forms.Textarea(attrs={
        'rows': 5,
        'cols': 50,
        'placeholder': '지금 뭘 하고 계신가요?',
        
    }))
    
    class Meta:
        model = Post
        # input을 만들 칼럼 값을 list로 만들어 넣어줌
        fields = ['content', 'image']

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostModelForm, CommentForm
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

# Create your views here.
@login_required
def create(request):
    # 만약 GET 요청이 오면
    if request.method == "POST":
        # 글을 작성하기
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            
            return redirect('posts:list')
    # 아니면 (GET 요청이 오면)
    else:
        # post를 작성하는 폼을 가져와 template에서 보여줌
        form = PostModelForm()
        context = {
            'form': form
        }
        return render(request, 'posts/create.html', context)

@login_required
def list(request):
    # 모든 Post를 보여줌
    # posts = Post.objects.all()
    # => 수정: 접속한 유저가 팔로잉한 유저들의 Post만 보여준다.
    #posts = []
    #for following in request.user.followings.all():
    #    posts.extend(Post.objects.filter(user=following))
    
    posts = Post.objects.filter(user__in=request.user.followings.values('id').order_by('-pk'))
    
    comment_form = CommentForm()
    context = {
        'posts':posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/list.html', context)

@login_required    
def delete(request, post_id):
    post = Post.objects.get(pk=post_id)
    
    if post.user != request.user:
        return redirect('posts:list')
    
    post.delete()
    return redirect('posts:list')

@login_required
def update(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    if post.user != request.user:
        return redirect('posts:list')
        
    if request.method == "POST":
        # 수정내용 DB에 반영
        form = PostModelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
    else:
        # 수정 내용 편집
        form = PostModelForm(instance=post)
        context = {
            'form': form,
        }
        return render(request, 'posts/update.html', context)

@login_required
def create_comments(request, post_id):
    comment_form = CommentForm(request.POST)
    
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post_id = post_id
        comment.save()
        
        return redirect('posts:list')

@login_required        
def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    # 특정 유저가 특정 포스트를 좋아요할 때
    # 만약 좋아요가 되어있다면,
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    # -> 좋아요를 해제하고,
    # 아니면
    else:
        post.like_users.add(request.user)
    # -> 좋아요를 한다.
    return redirect('posts:list')
    

posts/templates/posts/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1>새로운 Post 작성하기</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">업로드</button>
  {% endbuttons %}
</form>

{% endblock%}

posts/templates/posts/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <!-- 모든 post를 보여줌-->
  <div class="row justify-content-center">
      {% for post in posts %}
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          <span><a href="{% url 'profile' post.user.username %}">{{ post.user.username }}</a></span>
        </div>
        {% if post.image.url %}
        <img src="{{ post.image.url }}" class="card-img-top" alt="...">
        {% endif %}
        
        <div class="card-body">
          <a href="{% url 'posts:like' post.id %}">
            <!-- 만약 현재 접속한 유저가 좋아요 했었으면 -->
            {% if user in post.like_users.all %}
            <i class="fas fa-heart"></i>
            <!-- 아니면 -->
            {% else %}
            <i class="far fa-heart"></i>
            {% endif %}
          </a>
          <p class="card-text">
            {{ post.like_users.count }}명이 좋아합니다.
          </p>
        </div>
        
        <div class="card-body">
          <p class="card-text">{{ post.content }}</p>
          <!-- 본인의 글만 삭제, 수정 버튼이 보이도록 -->
          {% if request.user == post.user %}
          <a class="btn btn-danger" href="{% url 'posts:delete' post.id %}">삭제</a>
          <a class="btn btn-success" href="{% url 'posts:update' post.id %}">수정</a>
          {% endif %}
          
          <form method="POST" action="{% url 'posts:create_comments' post.id %}">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <button type="submit" class="btn btn-warning">댓글</button>
          </form>
          
          {% for comment in post.comment_set.all %}
          <div class="card-text">
            <strong>{{ comment.user }}</strong> {{ comment.content }}
          </div>
          {% endfor %}
          
        </div>
      </div>
      {% endfor %}
  </div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1>Post 수정하기</h1>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">업로드</button>
  {% endbuttons %}
</form>

{% endblock%}